"""
Interpreter DAG Analyzer.
===========================

Description
-----------
Direct Acyclic Graph.
"""

import copy
from collections import defaultdict
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set

import networkx as nx

from vtlengine.AST import (
    AST,
    Aggregation,
    Analytic,
    Assignment,
    BinOp,
    Constant,
    DefIdentifier,
    DPRuleset,
    DPValidation,
    EvalOp,
    HROperation,
    HRuleset,
    Identifier,
    JoinOp,
    MulOp,
    Operator,
    ParamOp,
    PersistentAssignment,
    RegularAggregation,
    Start,
    TimeAggregation,
    UDOCall,
    UnaryOp,
    Validation,
    VarID,
)
from vtlengine.AST.ASTTemplate import ASTTemplate
from vtlengine.AST.DAG._models import Schedule, StatementDeps
from vtlengine.AST.Grammar.tokens import (
    AS,
    BETWEEN,
    DROP,
    EXISTS_IN,
    FILL_TIME_SERIES,
    FLOW_TO_STOCK,
    INSTR,
    INTERSECT,
    KEEP,
    MEMBERSHIP,
    PERIOD_INDICATOR,
    RANDOM,
    RENAME,
    REPLACE,
    ROUND,
    SETDIFF,
    STOCK_TO_FLOW,
    SUBSTR,
    SYMDIFF,
    TIMESHIFT,
    TO,
    TRUNC,
    UNION,
)
from vtlengine.DataTypes import COMP_NAME_MAPPING
from vtlengine.Exceptions import SemanticError
from vtlengine.Model import Component, Dataset

# Operators that only accept datasets as input (never scalars).
# Grouped by AST node type for clarity.
DATASET_ONLY_MULOP = frozenset({UNION, INTERSECT, SETDIFF, SYMDIFF, EXISTS_IN})
DATASET_ONLY_UNARYOP = frozenset({FLOW_TO_STOCK, STOCK_TO_FLOW, PERIOD_INDICATOR})
DATASET_ONLY_BINOP = frozenset({MEMBERSHIP, TIMESHIFT})

# BinOp operators where the right operand must always be a scalar.
SCALAR_RIGHT_BINOP = frozenset({RANDOM})

# ParamOp operators where all params (not children) must be scalars.
SCALAR_PARAMS_PARAMOP = frozenset({ROUND, TRUNC, SUBSTR, REPLACE, INSTR})

# MulOp operators where children[1:] must be scalars (operand is children[0]).
SCALAR_TAIL_MULOP = frozenset({BETWEEN})

# Reserved component names generated by the engine (e.g., count() → int_var,
# check() → bool_var). These are never external inputs.
RESERVED_COMPONENT_NAMES = frozenset(COMP_NAME_MAPPING.values())


@dataclass
class DAGAnalyzer(ASTTemplate):
    udos: Optional[Dict[str, Any]] = None
    number_of_statements: int = 1
    dependencies: Dict[int, StatementDeps] = field(default_factory=dict)
    vertex: Dict[int, str] = field(default_factory=dict)
    edges: Dict[int, tuple] = field(default_factory=dict)  # type: ignore[type-arg]
    sorting: Optional[List[int]] = None

    # Handlers
    is_first_assignment: bool = False
    is_from_regular_aggregation: bool = False
    is_dataset: bool = False
    alias: Set[str] = field(default_factory=set)

    # Per-statement accumulator (reset between statements)
    current_deps: StatementDeps = field(default_factory=StatementDeps)
    _current_has_dataset_op: bool = False
    # Cross-statement unknown variable tracking
    unknown_variables: Set[str] = field(default_factory=set)
    # Outputs that were consumed via unknown_variables (RegularAggregation context)
    _resolved_from_unknown: Set[str] = field(default_factory=set)
    # UDO names that have at least one dataset-typed parameter
    _udos_with_dataset_params: Set[str] = field(default_factory=set)

    @classmethod
    def ds_structure(cls, ast: AST) -> Schedule:
        dag = cls()
        dag.visit(ast)
        return dag._ds_usage_analysis()

    def _ds_usage_analysis(self) -> Schedule:
        """Analyze dataset dependencies to build insertion/deletion schedules."""
        deletion: Dict[int, List[str]] = defaultdict(list)
        insertion: Dict[int, List[str]] = defaultdict(list)
        all_outputs: Set[str] = set()
        persistent_datasets: List[str] = []

        # Reverse index: dataset_name -> last statement that uses it as input
        last_consumer: Dict[str, int] = {}
        for key, statement in self.dependencies.items():
            for input_name in statement.inputs:
                last_consumer[input_name] = key

        # Schedule deletion for statement outputs at their last consumer
        for key, statement in self.dependencies.items():
            reference = statement.outputs + statement.persistent
            if (
                len(statement.persistent) == 1
                and statement.persistent[0] not in persistent_datasets
            ):
                persistent_datasets.append(statement.persistent[0])
            ds_name = reference[0]
            all_outputs.add(ds_name)
            deletion[last_consumer.get(ds_name, key)].append(ds_name)

        # Schedule insertion (first use) and deletion (last use) for global inputs
        global_inputs: List[str] = []
        global_set: Set[str] = set()
        for key, statement in self.dependencies.items():
            for element in statement.inputs:
                if element not in all_outputs and element not in global_set:
                    global_set.add(element)
                    global_inputs.append(element)
                    deletion[last_consumer.get(element, key)].append(element)
                    insertion[key].append(element)

        classification = self._classify_global_inputs(all_outputs, global_inputs, global_set)

        return Schedule(
            insertion=dict(insertion),
            deletion=dict(deletion),
            global_inputs=classification["global_inputs"],
            global_input_datasets=classification["global_input_datasets"],
            global_input_scalars=classification["global_input_scalars"],
            global_input_dataset_or_scalar=classification["global_input_dataset_or_scalar"],
            global_input_component_or_scalar=classification["global_input_component_or_scalar"],
            persistent=persistent_datasets,
            all_outputs=sorted(all_outputs),
        )

    def _classify_global_inputs(
        self,
        all_outputs: Set[str],
        global_inputs: List[str],
        global_set: Set[str],
    ) -> Dict[str, List[str]]:
        """Classify global inputs into datasets, scalars, and ambiguous categories."""
        scalar_outputs, comp_or_scalar = self._compute_scalar_outputs(all_outputs)

        # Identify definite dataset and scalar inputs
        definite_dataset_inputs: Set[str] = set()
        definite_scalar_inputs: Set[str] = set()
        for statement in self.dependencies.values():
            # Collect explicitly typed scalar inputs (e.g., UDO scalar params)
            for inp in statement.scalar_inputs:
                definite_scalar_inputs.add(inp)
            if statement.has_dataset_op:
                for inp in statement.dataset_inputs:
                    definite_dataset_inputs.add(inp)

        # Include component_or_scalar candidates in global_inputs
        for name in comp_or_scalar:
            if name not in global_set and name not in all_outputs:
                global_set.add(name)
                global_inputs.append(name)

        # Classify into four categories
        result: Dict[str, List[str]] = {
            "global_inputs": global_inputs,
            "global_input_datasets": [],
            "global_input_scalars": [],
            "global_input_dataset_or_scalar": [],
            "global_input_component_or_scalar": [],
        }

        for name in global_inputs:
            if name in comp_or_scalar:
                result["global_input_component_or_scalar"].append(name)
            elif name in definite_dataset_inputs:
                result["global_input_datasets"].append(name)
            elif name in definite_scalar_inputs or self._feeds_only_scalar_chains(
                name, scalar_outputs
            ):
                result["global_input_scalars"].append(name)
            else:
                result["global_input_dataset_or_scalar"].append(name)

        return result

    def _compute_scalar_outputs(self, all_outputs: Set[str]) -> tuple[Set[str], Set[str]]:
        """Compute scalar outputs via propagation and component/scalar candidates."""
        scalar_outputs: Set[str] = set()
        for statement in self.dependencies.values():
            reference = statement.outputs + statement.persistent
            if not reference:
                continue
            ds_name = reference[0]
            is_constant_assignment = not statement.has_dataset_op and not statement.inputs
            if is_constant_assignment or ds_name in self._resolved_from_unknown:
                scalar_outputs.add(ds_name)

        comp_or_scalar: Set[str] = set()
        for statement in self.dependencies.values():
            for uv in statement.unknown_variables:
                if uv not in all_outputs:
                    comp_or_scalar.add(uv)

        # Propagate: statements with no dataset ops where all inputs are known scalars
        changed = True
        while changed:
            changed = False
            for statement in self.dependencies.values():
                reference = statement.outputs + statement.persistent
                if not reference:
                    continue
                ds_name = reference[0]
                if ds_name in scalar_outputs or statement.has_dataset_op:
                    continue
                if statement.inputs and all(
                    inp in scalar_outputs or inp in comp_or_scalar for inp in statement.inputs
                ):
                    scalar_outputs.add(ds_name)
                    changed = True

        return scalar_outputs, comp_or_scalar

    def _feeds_only_scalar_chains(self, name: str, scalar_outputs: Set[str]) -> bool:
        """Check if a global input feeds only into scalar-output statements."""
        has_consumers = False
        for stmt in self.dependencies.values():
            if name not in stmt.inputs:
                continue
            has_consumers = True
            if stmt.has_dataset_op:
                return False
            reference = stmt.outputs + stmt.persistent
            if reference and reference[0] not in scalar_outputs:
                return False
        return has_consumers

    @classmethod
    def create_dag(cls, ast: Start) -> "DAGAnalyzer":
        dag = cls()
        dag.visit(ast)
        dag.load_vertex()
        dag.load_edges()
        try:
            dag._build_and_sort_graph("createDAG")
            if len(dag.edges) != 0:
                dag.sort_ast(ast)
            else:
                ml_statements: list = [
                    ml for ml in ast.children if not isinstance(ml, (HRuleset, DPRuleset, Operator))
                ]
                dag.check_overwriting(ml_statements)
            return dag
        except SemanticError:
            raise
        except Exception as error:
            raise SemanticError(code="1-3-2-0") from error

    def _build_and_sort_graph(self, error_op: str) -> None:
        """Build networkx DAG, perform topological sort, detect cycles."""
        edges = list(self.edges.values())
        graph = nx.DiGraph()
        graph.add_nodes_from(self.vertex)
        graph.add_edges_from(edges)

        try:
            result: list = []
            components = sorted(nx.weakly_connected_components(graph), key=min)
            for component in components:
                result.extend(nx.topological_sort(graph.subgraph(component)))
            self.sorting = result
        except nx.NetworkXUnfeasible:
            error_keys: Dict[int, Any] = {}
            for v in self.edges.values():
                aux_v0, aux_v1 = v[1], v[0]
                for iv in self.edges.values():
                    if aux_v0 == iv[0] and aux_v1 == iv[1]:
                        error_keys[aux_v0] = self.dependencies[aux_v0]
                        error_keys[aux_v1] = self.dependencies[aux_v1]
                        break
            raise SemanticError("1-3-2-3", op=error_op, nodes=error_keys) from None

    def load_vertex(self) -> None:
        for key, statement in self.dependencies.items():
            output = statement.outputs + statement.persistent + statement.unknown_variables
            if len(output) != 0:
                self.vertex[key] = output[0]

    def load_edges(self) -> None:
        if len(self.vertex) != 0:
            count_edges = 0
            ref_to_keys: Dict[str, int] = {}
            for key, statement in self.dependencies.items():
                reference = statement.outputs + statement.persistent
                if reference:
                    ref_to_keys[reference[0]] = key

            for sub_key, sub_statement in self.dependencies.items():
                for input_val in sub_statement.inputs:
                    if input_val in ref_to_keys:
                        key = ref_to_keys[input_val]
                        self.edges[count_edges] = (key, sub_key)
                        count_edges += 1

    def sort_elements(self, statements: list) -> list:
        return [statements[x - 1] for x in self.sorting]  # type: ignore[union-attr]

    def check_overwriting(self, statements: list) -> None:
        seen: Set[str] = set()
        for statement in statements:
            if statement.left.value in seen:
                raise SemanticError("1-2-2", varId_value=statement.left.value)
            seen.add(statement.left.value)

    def sort_ast(self, ast: AST) -> None:
        statements_nodes = ast.children
        hr_statements: list = [node for node in statements_nodes if isinstance(node, HRuleset)]
        dp_statements: list = [node for node in statements_nodes if isinstance(node, DPRuleset)]
        do_statements: list = [node for node in statements_nodes if isinstance(node, Operator)]
        ml_statements: list = [
            node
            for node in statements_nodes
            if not isinstance(node, (HRuleset, DPRuleset, Operator))
        ]

        intermediate = self.sort_elements(ml_statements)
        self.check_overwriting(intermediate)
        ast.children = hr_statements + dp_statements + do_statements + intermediate

    def statement_structure(self) -> StatementDeps:
        result = StatementDeps(
            inputs=[
                inp for inp in self.current_deps.inputs if inp not in self.current_deps.outputs
            ],
            outputs=list(self.current_deps.outputs),
            persistent=list(self.current_deps.persistent),
            unknown_variables=list(self.current_deps.unknown_variables),
            has_dataset_op=self._current_has_dataset_op,
            dataset_inputs=list(self.current_deps.dataset_inputs),
            scalar_inputs=list(self.current_deps.scalar_inputs),
        )
        self.unknown_variables.update(self.current_deps.unknown_variables)
        return result

    """______________________________________________________________________________________


                                Start of visiting AST nodes.

    _______________________________________________________________________________________"""

    def visit_Start(self, node: Start) -> None:
        """
        Start: (children)

        Basic usage:

            for child in node.children:
                self.visit(child)
        """
        udos = {}
        udos_with_ds: Set[str] = set()
        for ast_element in node.children:
            if isinstance(ast_element, Operator):
                udos[ast_element.op] = ast_element
                for p in ast_element.parameters:
                    if isinstance(p.type_, Dataset):
                        udos_with_ds.add(ast_element.op)
                        break
        self.udos = udos
        self._udos_with_dataset_params = udos_with_ds
        for child in node.children:
            if isinstance(child, (Assignment, PersistentAssignment)):
                self.is_first_assignment = True
                self.visit(child)

                self.dependencies[self.number_of_statements] = self.statement_structure()
                self.number_of_statements += 1
                self.alias = set()
                self.current_deps = StatementDeps()
                self._current_has_dataset_op = False

        aux = copy.copy(self.unknown_variables)
        for variable in aux:
            for _number_of_statement, dependency in self.dependencies.items():
                if variable in dependency.outputs:
                    self.unknown_variables.discard(variable)
                    self._resolved_from_unknown.add(variable)
                    for _ns2, dep2 in self.dependencies.items():
                        if variable in dep2.unknown_variables:
                            dep2.unknown_variables.remove(variable)
                            dep2.inputs.append(variable)

    def visit_Assignment(self, node: Assignment) -> None:
        if self.is_first_assignment:
            self.current_deps.outputs.append(node.left.value)
            self.is_first_assignment = False

        self.visit(node.right)

    def visit_PersistentAssignment(self, node: PersistentAssignment) -> None:
        if self.is_first_assignment:
            self.current_deps.persistent.append(node.left.value)
            self.is_first_assignment = False

        self.visit(node.right)

    def visit_RegularAggregation(self, node: RegularAggregation) -> None:
        self._current_has_dataset_op = True
        if isinstance(node.dataset, VarID) and node.dataset.value not in self.alias:
            self.current_deps.dataset_inputs.append(node.dataset.value)
        self.visit(node.dataset)
        if node.op in [KEEP, DROP, RENAME]:
            return
        for child in node.children:
            self.is_from_regular_aggregation = True
            self.visit(child)
            self.is_from_regular_aggregation = False

    def visit_BinOp(self, node: BinOp) -> None:
        if node.op in DATASET_ONLY_BINOP:
            self._current_has_dataset_op = True
            if isinstance(node.left, VarID) and node.left.value not in self.alias:
                self.current_deps.dataset_inputs.append(node.left.value)
            self.is_dataset = True
            self.visit(node.left)
            self.is_dataset = False
            self.visit(node.right)
        elif node.op in SCALAR_RIGHT_BINOP:
            self.visit(node.left)
            if isinstance(node.right, VarID) and node.right.value not in self.alias:
                self.current_deps.scalar_inputs.append(node.right.value)
            self.visit(node.right)
        elif node.op == AS or node.op == TO:
            self.visit(node.left)
            self.alias.add(node.right.value)
        else:
            self.visit(node.left)
            self.visit(node.right)

    def visit_MulOp(self, node: MulOp) -> None:
        if node.op in DATASET_ONLY_MULOP:
            self._current_has_dataset_op = True
            for child in node.children:
                if isinstance(child, VarID) and child.value not in self.alias:
                    self.current_deps.dataset_inputs.append(child.value)
        elif node.op in SCALAR_TAIL_MULOP:
            # First child is the operand (dual), rest are scalar-only params.
            for child in node.children[1:]:
                if isinstance(child, VarID) and child.value not in self.alias:
                    self.current_deps.scalar_inputs.append(child.value)
        for child in node.children:
            self.visit(child)

    def visit_UnaryOp(self, node: UnaryOp) -> None:
        if node.op in DATASET_ONLY_UNARYOP:
            self._current_has_dataset_op = True
            if isinstance(node.operand, VarID) and node.operand.value not in self.alias:
                self.current_deps.dataset_inputs.append(node.operand.value)
        self.visit(node.operand)

    def visit_VarID(self, node: VarID) -> None:
        if (
            not self.is_from_regular_aggregation or self.is_dataset
        ) and node.value not in self.alias:
            if node.value not in self.current_deps.inputs:
                self.current_deps.inputs.append(node.value)
        elif (
            self.is_from_regular_aggregation
            and node.value not in self.alias
            and not self.is_dataset
            and node.value not in RESERVED_COMPONENT_NAMES
            and node.value not in self.current_deps.unknown_variables
        ):
            self.current_deps.unknown_variables.append(node.value)

    def visit_Identifier(self, node: Identifier) -> None:
        if (
            node.kind == "DatasetID"
            and node.value not in self.alias
            and node.value not in self.current_deps.inputs
        ):
            self._current_has_dataset_op = True
            self.current_deps.inputs.append(node.value)
            self.current_deps.dataset_inputs.append(node.value)

    def visit_ParamOp(self, node: ParamOp) -> None:
        if self.udos and node.op in self.udos:
            if node.op in self._udos_with_dataset_params:
                self._current_has_dataset_op = True
            do_ast: Operator = self.udos[node.op]
            for i, arg in enumerate(node.params):
                if isinstance(arg, Constant):
                    continue
                param_type = do_ast.parameters[i].type_
                if type(param_type) is not Component:
                    is_ds = isinstance(param_type, Dataset)
                    if is_ds and isinstance(arg, VarID):
                        self.current_deps.dataset_inputs.append(arg.value)
                    elif not is_ds and isinstance(arg, VarID):
                        self.current_deps.scalar_inputs.append(arg.value)
                self.visit(arg)
        else:
            if node.op == FILL_TIME_SERIES:
                self._current_has_dataset_op = True
                for child in node.children:
                    if isinstance(child, VarID) and child.value not in self.alias:
                        self.current_deps.dataset_inputs.append(child.value)
            elif node.op in SCALAR_PARAMS_PARAMOP:
                for param in node.params:
                    if isinstance(param, VarID) and param.value not in self.alias:
                        self.current_deps.scalar_inputs.append(param.value)
            super(DAGAnalyzer, self).visit_ParamOp(node)

    def visit_Aggregation(self, node: Aggregation) -> None:
        self._current_has_dataset_op = True
        if node.operand is not None:
            if isinstance(node.operand, VarID) and node.operand.value not in self.alias:
                self.current_deps.dataset_inputs.append(node.operand.value)
            self.visit(node.operand)

    def visit_Analytic(self, node: Analytic) -> None:
        self._current_has_dataset_op = True
        # Inside RegularAggregation (calc/filter/etc.), analytic operands are always
        # component references — they cannot be external scalars, so skip them.
        if node.operand is not None and not self.is_from_regular_aggregation:
            self.visit(node.operand)

    def visit_JoinOp(self, node: JoinOp) -> None:
        self._current_has_dataset_op = True
        # Join clauses contain BinOp(AS) nodes; dataset aliases are handled via visit_BinOp.
        # Direct VarID children in clauses are dataset references.
        for clause in node.clauses:
            if isinstance(clause, BinOp) and clause.op == AS:
                if isinstance(clause.left, VarID) and clause.left.value not in self.alias:
                    self.current_deps.dataset_inputs.append(clause.left.value)
            elif isinstance(clause, VarID) and clause.value not in self.alias:
                self.current_deps.dataset_inputs.append(clause.value)
            self.visit(clause)

    def visit_UDOCall(self, node: UDOCall) -> None:
        node_args = (self.udos or {}).get(node.op)
        if not node_args:
            super().visit_UDOCall(node)
        else:
            if node.op in self._udos_with_dataset_params:
                self._current_has_dataset_op = True
            for p, param in zip(node_args.parameters, node.params):
                if isinstance(param, Constant):
                    continue
                if type(p.type_) is not Component:
                    is_ds = isinstance(p.type_, Dataset)
                    if is_ds and isinstance(param, VarID):
                        self.current_deps.dataset_inputs.append(param.value)
                    elif not is_ds and isinstance(param, VarID):
                        self.current_deps.scalar_inputs.append(param.value)
                    self.visit(param)

    def visit_HROperation(self, node: HROperation) -> None:
        """Visit HROperation node for dependency analysis."""
        self._current_has_dataset_op = True
        if isinstance(node.dataset, VarID) and node.dataset.value not in self.alias:
            self.current_deps.dataset_inputs.append(node.dataset.value)
        self.visit(node.dataset)

    def visit_DPValidation(self, node: DPValidation) -> None:
        """Visit DPValidation node for dependency analysis."""
        self._current_has_dataset_op = True
        if isinstance(node.dataset, VarID) and node.dataset.value not in self.alias:
            self.current_deps.dataset_inputs.append(node.dataset.value)
        self.visit(node.dataset)

    def visit_TimeAggregation(self, node: TimeAggregation) -> None:
        if node.operand is not None:
            self.visit(node.operand)

    def visit_Validation(self, node: Validation) -> None:
        # Don't force has_dataset_op here — let the inner expression determine it.
        # Dataset-only operators (exists_in, membership, etc.) set it themselves.
        self.visit(node.validation)
        if node.imbalance is not None:
            self.visit(node.imbalance)

    def visit_EvalOp(self, node: EvalOp) -> None:
        """Eval operands are always datasets (external SQL routine inputs)."""
        self._current_has_dataset_op = True
        for operand in node.operands:
            if isinstance(operand, VarID) and operand.value not in self.alias:
                self.current_deps.dataset_inputs.append(operand.value)
            self.visit(operand)


class HRDAGAnalyzer(DAGAnalyzer):
    def visit_HRuleset(self, node: HRuleset) -> None:
        """
        HRuleset: (name, element, rules)

        Basic usage:

            self.visit(node.element)
            for rule in node.rules:
                self.visit(rule)
        """
        if isinstance(node.element, list):
            for element in node.element:
                self.visit(element)
        else:
            self.visit(node.element)
        self.rules_ast = node.rules
        for rule in node.rules:
            self.is_first_assignment = True
            self.visit(rule)
            self.dependencies[self.number_of_statements] = self.statement_structure()

            self.number_of_statements += 1
            self.alias = set()
            self.current_deps = StatementDeps()

    def visit_DefIdentifier(self, node: DefIdentifier) -> None:  # type: ignore[override]
        """
        DefIdentifier: (value, kind)

        Basic usage:

            return node.value
        """
        if node.kind == "CodeItemID":
            if self.is_first_assignment:
                self.is_first_assignment = False
                self.current_deps.outputs.append(node.value)
            elif node.value not in self.current_deps.inputs:
                self.current_deps.inputs.append(node.value)
