name: Bug report
description: Report incorrect behavior in VTL Engine
type: Bug
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      options:
        - label: I have searched [existing issues](https://github.com/Meaningful-Data/vtlengine/issues?q=is%3Aissue) for duplicates
          required: true
        - label: I have read the [documentation](https://docs.vtlengine.meaningfuldata.eu)
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear, concise description of the problem.
    validations:
      required: true

  - type: textarea
    id: reproducible-example
    attributes:
      label: Reproducible Example
      description: >
        Please provide a self-contained script that reproduces the issue.
        Reports without reproducible examples may be closed.
      placeholder: |
        import pandas as pd
        from vtlengine import run

        script = """DS_r <- DS_1 * 10;"""

        data_structures = {
            "datasets": [
                {
                    "name": "DS_1",
                    "DataStructure": [
                        {"name": "Id_1", "type": "Integer", "role": "Identifier", "nullable": False},
                        {"name": "Me_1", "type": "Number", "role": "Measure", "nullable": True},
                    ],
                }
            ]
        }

        datapoints = {"DS_1": pd.DataFrame({"Id_1": [1, 2, 3], "Me_1": [10, 20, 30]})}

        result = run(script=script, data_structures=data_structures, datapoints=datapoints)
        print(result)
      render: python
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual
      description: What did you expect to happen, and what actually happened?
      placeholder: |
        Expected: ...
        Actual: ...
    validations:
      required: true

  - type: input
    id: vtlengine-version
    attributes:
      label: vtlengine version
      placeholder: e.g., 1.5.0
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: e.g., 3.12.0

  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g., Ubuntu 24.04, Windows 11, macOS 15

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Logs, stack traces, or sample data (redact secrets).
