name: Documentation
description: Report missing, incorrect, or unclear documentation
type: Task
labels: [documentation]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      options:
        - label: I have checked the [documentation](https://docs.vtlengine.meaningfuldata.eu) and the issue is not already addressed
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What documentation is missing, incorrect, or unclear?
    validations:
      required: true

  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Change
      description: Describe the improvement or correction needed.

  - type: input
    id: location
    attributes:
      label: Location
      description: Page, section, or URL affected.
      placeholder: e.g., https://docs.vtlengine.meaningfuldata.eu/walkthrough.html

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: References, links, or examples that support the change.
