name: Feature request
description: Suggest an idea or improvement
type: Feature
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      options:
        - label: I have searched [existing issues](https://github.com/Meaningful-Data/vtlengine/issues?q=is%3Aissue) for duplicates
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What problem would this feature solve? e.g., "I wish I could use VTL Engine to ..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: >
        How should the feature work? Include VTL syntax, API signatures,
        or code examples if applicable.
      render: python
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Other approaches you thought about and why they are insufficient.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: References, links, or examples. Note required data inputs/outputs if relevant.
