from pathlib import Path
from typing import Any, Dict

output_filepath = Path(__file__).parent.parent.parent.parent / "Docs" / "error_messages.rst"

# Import centralised messages
# from vtlengine.Exceptions.messages import centralised_messages


def generate_errors_rst(file_path: Path, messages: Dict[str, Any]) -> None:
    """
    Generates an RST file with a grid of error codes, messages, and descriptions.
    """

    def sort_key(code: str) -> Any:
        return tuple(int(part) for part in code.split("-"))

    path = Path(file_path)
    lines = []
    lines.append("Error Messages")
    lines.append("################")
    lines.append("")
    lines.append(
        "This document provides a complete list of all error messages generated by the VTL engine. "
        "Each entry includes the error code, the corresponding message, and a brief description "
        "to help users to understand the cause of the issue."
    )
    lines.append("")
    lines.append("The following legend explains the error code patterns used in the VTL engine:")
    lines.append("")
    category_header = "Category"
    pattern_header = "Pattern"

    legend_rows = [
        ("INPUT ERRORS", "0-1-X-X = Input Validation Errors\n"),
        ("", "0-3-X-X = DataLoad Errors"),
        ("SEMANTIC ERRORS", "1-1-X-X = Operators Semantic Errors\n"),
        ("", "1-3-X-X = Semantic Analyzer Errors\n"),
        ("", "1-4-X-X = AST Errors"),
        ("RUNTIME ERRORS", "2-X-X-X = RunTime Operator Errors"),
    ]

    max_cat = max(len(category_header), max(len(row[0]) for row in legend_rows))
    max_pat = max(len(pattern_header), max(len(row[1]) for row in legend_rows))

    sep_legend = f"{'=' * max_cat}  {'=' * max_pat}"

    lines.append(sep_legend)
    lines.append(f"{category_header.ljust(max_cat)}  {pattern_header.ljust(max_pat)}")
    lines.append(sep_legend)

    for cat, pat in legend_rows:
        lines.append(f"{cat.ljust(max_cat)}  {pat.ljust(max_pat)}")

    lines.append(sep_legend)
    lines.append("")
    lines.append("The following table contains all available error codes:")
    lines.append("")
    headers = ["Code", "Message", "Description"]
    max_lengths = [len(h) for h in headers]

    for code, info in messages.items():
        if isinstance(info, dict):
            message = info.get("message", "")
            description = info.get("description", "")
        else:
            message = str(info)
            description = ""
        max_lengths[0] = max(max_lengths[0], len(code))
        max_lengths[1] = max(max_lengths[1], len(message))
        max_lengths[2] = max(max_lengths[2], len(description))

    sep = "  ".join("=" * length for length in max_lengths)
    lines.append(sep)
    header_line = "  ".join(h.ljust(max_lengths[i]) for i, h in enumerate(headers))
    lines.append(header_line)
    lines.append(sep)

    for code in sorted(messages.keys(), key=sort_key):
        info = messages[code]
        if isinstance(info, dict):
            message = info.get("message", "")
            description = info.get("description", "")
        else:
            message = str(info)
            description = ""

        row = "  ".join(s.ljust(max_lengths[i]) for i, s in enumerate([code, message, description]))
        lines.append(row)

    lines.append(sep)

    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"RST generated in {path}")
