DUCKDB_TO_VTL_TYPES = {
    # Integers
    "TINYINT": "Integer",
    "SMALLINT": "Integer",
    "INT": "Integer",
    "INT32": "Integer",
    "INTEGER": "Integer",
    "BIGINT": "Integer",
    "UBIGINT": "Integer",
    "UINTEGER": "Integer",
    # Numbers
    "REAL": "Number",
    "FLOAT": "Number",
    "FLOAT4": "Number",
    "FLOAT8": "Number",
    "DOUBLE": "Number",
    "DECIMAL": "Number",
    "NUMERIC": "Number",
    # Strings
    "VARCHAR": "String",
    "CHAR": "String",
    "TEXT": "String",
    "UUID": "String",
    # Other
    "BOOLEAN": "Boolean",
    "DATE": "Date",
    "TIME": "Time",
    "TIMESTAMP": "Datetime",
    "TIMESTAMPTZ": "Datetime",
    "BLOB": "Binary",
}
