name: Publish package

run-name: "Publish package ${{ github.event.client_payload.tag_name || github.event.release.tag_name || '' }}"

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ release-published ]

permissions:
  contents: read

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Build package
        run: poetry build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          attestations: true
